title: My Personal Site
email: my-email@example.com
description: >- 
  A simple Jekyll site for showcasing your work and ideas.
baseurl: "" 
url: "https://edobox.github.io" 
theme: minima
plugins:
  - jekyll-feed
